//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header(){
  return (
    <header className="bg-[#4A4E69] py-4">
      <div className="container mx-auto px-4">
        <nav className="flex items-center justify-end h-16">
          <div>
            <Link href="/" className="text-lg font-semibold text-[#F9F5F2] hover:text-[#9A8C98]">
              Home
            </Link>
            <Link href="/projects" className="ml-15 text-lg font-semibold text-[#F9F5F2] hover:text-[#9A8C98]">
              Projects
            </Link>
            <Link href="/photography" className="ml-15 text-lg font-semibold text-[#F9F5F2] hover:text-[#9A8C98]">
              Photography
            </Link> 
            <Link href="/research" className="ml-15 text-lg font-semibold text-[#F9F5F2] hover:text-[#9A8C98]">
              Research
            </Link> 
            <Link href="/about" className="ml-15 text-lg font-semibold text-[#F9F5F2] hover:text-[#9A8C98]">
              About 
            </Link>
            <Link href="/contact" className="ml-15 text-lg font-semibold text-[#F9F5F2] hover:text-[#9A8C98]">
              Contact
            </Link>
          </div>
        </nav>
      </div>
    </header>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children} 
      </body>
    </html>
  );
}
